#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Iarch/arm/mach-msm/qdsp6v2
EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_MACH_LGE_I_BOARD_BELL)	+= board_i_bell.o
obj-$(CONFIG_MACH_LGE_I_BOARD_BELL)	+= platform_i_bell_bt.o
obj-$(CONFIG_MACH_LGE_I_BOARD_BELL)	+= platform_i_bell_camera.o
obj-$(CONFIG_MACH_LGE_I_BOARD_BELL)	+= platform_i_bell_input.o
obj-$(CONFIG_MACH_LGE_I_BOARD_BELL)	+= platform_i_bell_misc.o
#obj-$(CONFIG_MACH_LGE_I_BOARD_BELL)	+= platform_i_bell_mmc.o
obj-$(CONFIG_MACH_LGE_I_BOARD_BELL)	+= platform_i_bell_panel.o
obj-$(CONFIG_MACH_LGE_I_BOARD_BELL)	+= platform_i_bell_snd.o
obj-$(CONFIG_MACH_LGE_I_BOARD_BELL)	+= gpiomux_i_bell.o
obj-$(CONFIG_MACH_LGE_I_BOARD_BELL)	+= devices_i_bell.o
