#platform.team@lge.com	2011.01

EXTRA_CFLAGS += -Iarch/arm/mach-msm
EXTRA_CFLAGS += -Iarch/arm/mach-msm/qdsp6v2
EXTRA_CFLAGS += -Ilge/include

obj-$(CONFIG_MACH_LGE_I_BOARD_TLS)	+= board_j_tls.o
obj-$(CONFIG_MACH_LGE_I_BOARD_TLS)	+= platform_j_tls_bt.o
obj-$(CONFIG_MACH_LGE_I_BOARD_TLS)	+= platform_j_tls_camera.o
obj-$(CONFIG_MACH_LGE_I_BOARD_TLS)	+= platform_j_tls_input.o
obj-$(CONFIG_MACH_LGE_I_BOARD_TLS)	+= platform_j_tls_misc.o
#obj-$(CONFIG_MACH_LGE_I_BOARD_TLS)	+= platform_j_tls_mmc.o
obj-$(CONFIG_MACH_LGE_I_BOARD_TLS)	+= platform_j_tls_panel.o
obj-$(CONFIG_MACH_LGE_I_BOARD_TLS)	+= platform_j_tls_snd.o
obj-$(CONFIG_MACH_LGE_I_BOARD_TLS)	+= gpiomux_j_tls.o
obj-$(CONFIG_MACH_LGE_I_BOARD_TLS)	+= devices_j_tls.o
